spring.application.name=gateway
server.port=8080
spring.sleuth.sampler.probability=1.0
management.endpoints.web.exposure.include=*
eureka.client.register-with-eureka=true
spring.zipkin.base-url=http://localhost:9411
## Product Service
#spring.cloud.gateway.routes[0].id=product
#spring.cloud.gateway.routes[0].uri=lb://product
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**
#spring.cloud.gateway.routes[0].filters=AuthFilter
#
## User Service
#spring.cloud.gateway.routes[1].id=user
#spring.cloud.gateway.routes[1].uri=lb://user
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
#spring.cloud.gateway.routes[1].filters=AuthFilter
#
## Order Service
#spring.cloud.gateway.routes[2].id=order
#spring.cloud.gateway.routes[2].uri=lb://order
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/order/**
#spring.cloud.gateway.routes[2].filters=AuthFilter
#
## Cart Service (separate route or same service)
#spring.cloud.gateway.routes[3].id=order
#spring.cloud.gateway.routes[3].uri=lb://order
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/cart/**
#spring.cloud.gateway.routes[3].filters=AuthFilter

