spring.application.name=config-server
#spring.cloud.config.server.git.uri=https://github.com/baibhavdatta21/app-configuration
#spring.cloud.config.server.git.username=${GIT_USER}
#spring.cloud.config.server.git.password=${GIT_TOKEN}
#spring.profiles.active=jdbc
#spring.datasource.url=jdbc:mysql://localhost:3306/configdb
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.cloud.config.server.jdbc.sql=select prop_key, prop_value from properties where application=? and profile=? and label=?
#spring.cloud.config.server.jdbc.default-label=main
spring.profiles.active=native
spring.cloud.config.server.native.search-location=C:/Java_Projects/Updated_Ecom_Project/config-server/src/main/resources/config
server.port=8888