#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.url= jdbc:postgresql://localhost:5432/userdb
#spring.datasource.username=embarkx
#spring.datasource.password=embarkx
#spring.jpa.database=POSTGRESQL
server.port=8082
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=${USER_DB_URL}
spring.datasource.username=${USER_DB_USERNAME}
spring.datasource.password=${USER_DB_PASSWORD}
spring.jpa.database=MYSQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1